using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ToDo.Core.Models
{
    public class TaskModel
    {

        // task id (Auto generated using GUID)
        public string Id { get; set; }

        // actual task , set a limit of string length to 100 characters;
        [StringLength(100)]
        [DisplayName("Tasks")]
        public string TaskString { get; set; }

        public TaskModel()
        {
            // when ever a task is created, autogenerated id for it
            this.Id = Guid.NewGuid().ToString();
        }
    }
}
